# fly.toml app configuration file generated for black-sun-6864 on 2023-07-16T21:32:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-sun-6864"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
